version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_DB: test
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27023:27017


# npm i prisma && npm i -D @prisma/client
# npx prisma init
# npx prisma generat [uuid]
# docker-compose up -d
# docker exec -it mongodb mongosh
# docker images
# docker ps
# docker ps -a
# mongodb://root:example@localhost:27023

# docker start
# docker stop
# docker ps
# docker-compose stop
# docker-compose up
# docker images
# docker-compose exec mongodb mongosh -u mongo -p example
# show dbs
# use admin
# show collections
# db.user.drop()
# db.lnwza.find()

#npx prisma db push
#DATABASE_URL="mongodb://mongo:example@localhost:27023/lnwza?authSource=admin"
#https://www.youtube.com/watch?v=mj5MxsEiHe8
#https://github.com/prisma/prisma/blob/main/docker/mongodb_replica/Dockerfile